name: firebase_chat
description: Chat with firebase
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^3.2.0
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
