name: secure_messaging
description: Secure end-to-end messaging using RSA encryption.
version: 1.1.2
repository: https://github.com/ToxicAura60/secure_messaging

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  equatable: ^2.0.7
  path_provider: ^2.1.5
  pointycastle: ^3.9.1
  rsa_cipher: ^1.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
